site_name: TSClient Docs
markdown_extensions:
    - codehilite
theme: readthedocs
# site_url: https://temporasanguinis.it/client
repo_url: https://github.com/temporasanguinis/TS2-Client
site_dir: browser/static/docs

nav:
    - 'TSClient Home': '/'
    - 'Docs Home': 'README.md'
    - 'Scripting API': 'scripting.md'
