name: Build/release

on:
  push:
    tags:
      # Build on every tag in the form v1.2.3-something.4
      - 'v*'

jobs:
  
  release-web:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: cd browser && npm install
        
      - name: Build
        run: cd browser && npm run build && cd ./../telnet_proxy && npm install && npm run build && npm run webpack
          
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          directory: './browser/dist'
          type: 'zip'
          filename: '../../release-web.zip'
          path: './public'
          exclusions: '*.git* /*node_modules/* .editorconfig'

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          updateOnlyUnreleased: true
          prerelease: true
          artifacts: "release-web.zip"
          
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          updateOnlyUnreleased: true
          prerelease: true
          artifacts: "./telnet_proxy/dist/telnet_proxy/bundle/telnet_proxy.js"
